const TRADUCOES = [
  { palavra: 'guard', traducao: 'Guarda', exemplo: "Don't let them pass your guard." },
  { palavra: 'sweep', traducao: 'Raspagem', exemplo: 'Sweep from here!' },
  { palavra: 'pass', traducao: 'Passagem', exemplo: 'Pass the guard!' },
  { palavra: 'mount', traducao: 'Montada', exemplo: 'Keep pressure from mount.' },
  { palavra: 'submit', traducao: 'Finalizar', exemplo: 'Go for the submission!' },
  { palavra: 'tap', traducao: 'Bater / Desistir', exemplo: 'Tap out to avoid injury.' },
  { palavra: 'choke', traducao: 'Estrangulamento', exemplo: 'Sink the choke deeper!' },
  { palavra: 'armbar', traducao: 'Chave de braço', exemplo: 'Extend the arm fully to finish the armbar.' },
  { palavra: 'triangle', traducao: 'Triângulo', exemplo: 'Squeeze your legs to finish the triangle.' },
  { palavra: 'hook', traducao: 'Gancho', exemplo: 'Set your hooks to control from the back.' },
  { palavra: 'base', traducao: 'Base / Equilíbrio', exemplo: 'Keep a strong base.' },
  { palavra: 'pressure', traducao: 'Pressão', exemplo: 'Apply pressure to exhaust him.' },
  { palavra: 'posture', traducao: 'Postura', exemplo: 'Watch your posture!' },
  { palavra: 'grip', traducao: 'Pegada', exemplo: 'Break the grip before you pass.' },
  { palavra: 'distance', traducao: 'Distância', exemplo: 'Control the distance!' },
  { palavra: 'hip', traducao: 'Quadril', exemplo: 'Use your hips!' },
  { palavra: 'elbow', traducao: 'Cotovelo', exemplo: 'Block the hip with your elbow.' },
  { palavra: 'defend', traducao: 'Defender', exemplo: 'Defend the submission!' },
  { palavra: 'attack', traducao: 'Atacar', exemplo: 'Chain your attacks together.' },
  { palavra: 'control', traducao: 'Controlar', exemplo: 'Control the position.' },
  { palavra: 'escape', traducao: 'Escapar', exemplo: 'Hip escape to recover guard.' },
  { palavra: 'position', traducao: 'Posição', exemplo: 'Stabilize the position first.' },
  { palavra: 'side control', traducao: 'Controle lateral', exemplo: 'Apply pressure from side control.' },
  { palavra: 'back mount', traducao: 'Pegada nas costas', exemplo: 'Take the back and set your hooks.' },
  { palavra: 'half guard', traducao: 'Meia guarda', exemplo: 'Fight for the underhook from half guard.' },
  { palavra: 'underhook', traducao: 'Underhook', exemplo: 'Fight for the underhook!' },
  { palavra: 'overhook', traducao: 'Overhook', exemplo: 'Secure the overhook.' },
  { palavra: 'frame', traducao: 'Frame / Estrutura', exemplo: 'Use your arms as frames to create space.' },
  { palavra: 'shrimp', traducao: 'Fuga de quadril', exemplo: 'Shrimp to recover your guard.' },
  { palavra: 'bridge', traducao: 'Ponte', exemplo: 'Bridge and roll to escape mount.' },
  { palavra: 'sprawl', traducao: 'Sprawl', exemplo: 'Sprawl to defend the takedown.' },
  { palavra: 'takedown', traducao: 'Derrubada', exemplo: 'Shoot for the takedown.' },
  { palavra: 'clinch', traducao: 'Clinch', exemplo: 'Control from the clinch.' },
  { palavra: 'knee slide', traducao: 'Passagem pelo joelho', exemplo: 'Slide your knee to pass.' },
  { palavra: 'leg drag', traducao: 'Arrastar a perna', exemplo: 'Drag the leg to pass the guard.' },
  { palavra: 'De La Riva', traducao: 'Guarda De La Riva', exemplo: 'Set the DLR hook.' },
  { palavra: 'lasso', traducao: 'Guarda Lasso', exemplo: 'Wrap the lasso around his arm.' },
  { palavra: 'X-guard', traducao: 'Guarda X', exemplo: 'Enter the X-guard to sweep.' },
  { palavra: 'butterfly', traducao: 'Guarda Borboleta', exemplo: 'Lift with the butterfly guard.' },
  { palavra: 'collar', traducao: 'Gola', exemplo: 'Control the collar to break posture.' },
  { palavra: 'sleeve', traducao: 'Manga', exemplo: 'Grip the sleeve for control.' },
  { palavra: 'lapel', traducao: 'Lapela', exemplo: 'Use the lapel grip.' },
  { palavra: 'kimono', traducao: 'Kimono / Gi', exemplo: 'Use the kimono grips.' },
  { palavra: 'roll', traducao: 'Rolar / Sparring', exemplo: "Let's roll!" },
  { palavra: 'drill', traducao: 'Drilling / Praticar', exemplo: 'Drill to build muscle memory.' },
  { palavra: 'sparring', traducao: 'Treino vivo', exemplo: 'Test your techniques in sparring.' },
  { palavra: 'submission', traducao: 'Finalização', exemplo: 'Go for the submission!' },
  { palavra: 'rear naked choke', traducao: 'Mata-leão', exemplo: 'Set your hooks and go for the RNC.' },
  { palavra: 'Ezekiel choke', traducao: 'Estrangulamento Ezequiel', exemplo: 'Four fingers inside for the Ezekiel.' },
  { palavra: 'wrist lock', traducao: 'Chave de pulso', exemplo: 'Apply the wrist lock carefully.' },
  { palavra: 'heel hook', traducao: 'Chave de calcanhar', exemplo: 'Enter the heel hook position.' },
  { palavra: 'kneebar', traducao: 'Chave de joelho', exemplo: 'Lock the kneebar to finish.' },
  { palavra: 'toehold', traducao: 'Chave de tornozelo', exemplo: 'Apply the toehold submission.' },
  { palavra: 'stabilize', traducao: 'Estabilizar', exemplo: 'Stabilize the position first.' },
  { palavra: 'pressure', traducao: 'Pressão', exemplo: 'Apply pressure to exhaust him.' },
  { palavra: 'momentum', traducao: 'Momentum / Impulso', exemplo: 'Use momentum to finish the sweep.' },
  { palavra: 'timing', traducao: 'Timing / Momento certo', exemplo: 'Good timing is everything.' },
  { palavra: 'reaction', traducao: 'Reação', exemplo: 'React to his defense.' },
  { palavra: 'chain', traducao: 'Encadear', exemplo: 'Chain your techniques together.' },
  { palavra: 'flow', traducao: 'Fluir', exemplo: 'Relax and flow.' },
  { palavra: 'off balance', traducao: 'Desequilíbrio', exemplo: 'Off balance them before the sweep.' },
  { palavra: 'inside position', traducao: 'Posição interna', exemplo: 'Fight for the inside position.' },
  { palavra: 'seatbelt', traducao: 'Pegada de cinto', exemplo: 'Use the seatbelt grip from the back.' },
  { palavra: 'mat', traducao: 'Tatame', exemplo: 'Every day on the mat counts.' },
  { palavra: 'tap out', traducao: 'Bater / Desistir', exemplo: 'Tap out to avoid injury.' },
  { palavra: 'oss', traducao: 'Oss! (saudação)', exemplo: 'Oss! Show respect.' },
  { palavra: 'injury', traducao: 'Lesão', exemplo: 'Tap early to prevent injury.' },
  { palavra: 'technique', traducao: 'Técnica', exemplo: 'Focus on technique, not strength.' },
  { palavra: 'muscle memory', traducao: 'Memória muscular', exemplo: 'Drill to build muscle memory.' },
];

module.exports = TRADUCOES;